/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Search } from "./classes/search.class";
export { Search } from "./classes/search.class";
export namespace Components {
    interface YSearch {
        "apiKey": string;
        "channelId": string;
    }
    interface YwuiProfileInfo {
        "apiKey": string;
        "channelId": string;
        "showDescription": boolean;
    }
    interface YwuiVideoList {
        "apiKey": string;
        "channelId": string;
    }
}
export interface YSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYSearchElement;
}
declare global {
    interface HTMLYSearchElement extends Components.YSearch, HTMLStencilElement {
    }
    var HTMLYSearchElement: {
        prototype: HTMLYSearchElement;
        new (): HTMLYSearchElement;
    };
    interface HTMLYwuiProfileInfoElement extends Components.YwuiProfileInfo, HTMLStencilElement {
    }
    var HTMLYwuiProfileInfoElement: {
        prototype: HTMLYwuiProfileInfoElement;
        new (): HTMLYwuiProfileInfoElement;
    };
    interface HTMLYwuiVideoListElement extends Components.YwuiVideoList, HTMLStencilElement {
    }
    var HTMLYwuiVideoListElement: {
        prototype: HTMLYwuiVideoListElement;
        new (): HTMLYwuiVideoListElement;
    };
    interface HTMLElementTagNameMap {
        "y-search": HTMLYSearchElement;
        "ywui-profile-info": HTMLYwuiProfileInfoElement;
        "ywui-video-list": HTMLYwuiVideoListElement;
    }
}
declare namespace LocalJSX {
    interface YSearch {
        "apiKey"?: string;
        "channelId"?: string;
        "onSearchResult"?: (event: YSearchCustomEvent<Search>) => void;
    }
    interface YwuiProfileInfo {
        "apiKey"?: string;
        "channelId"?: string;
        "showDescription"?: boolean;
    }
    interface YwuiVideoList {
        "apiKey"?: string;
        "channelId"?: string;
    }
    interface IntrinsicElements {
        "y-search": YSearch;
        "ywui-profile-info": YwuiProfileInfo;
        "ywui-video-list": YwuiVideoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "y-search": LocalJSX.YSearch & JSXBase.HTMLAttributes<HTMLYSearchElement>;
            "ywui-profile-info": LocalJSX.YwuiProfileInfo & JSXBase.HTMLAttributes<HTMLYwuiProfileInfoElement>;
            "ywui-video-list": LocalJSX.YwuiVideoList & JSXBase.HTMLAttributes<HTMLYwuiVideoListElement>;
        }
    }
}
