/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface YProfileInfo {
        "apiKey": string;
        "channelDescription": string;
        "channelImage": string;
        "customDescription": boolean;
    }
}
declare global {
    interface HTMLYProfileInfoElement extends Components.YProfileInfo, HTMLStencilElement {
    }
    var HTMLYProfileInfoElement: {
        prototype: HTMLYProfileInfoElement;
        new (): HTMLYProfileInfoElement;
    };
    interface HTMLElementTagNameMap {
        "y-profile-info": HTMLYProfileInfoElement;
    }
}
declare namespace LocalJSX {
    interface YProfileInfo {
        "apiKey"?: string;
        "channelDescription"?: string;
        "channelImage"?: string;
        "customDescription"?: boolean;
    }
    interface IntrinsicElements {
        "y-profile-info": YProfileInfo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "y-profile-info": LocalJSX.YProfileInfo & JSXBase.HTMLAttributes<HTMLYProfileInfoElement>;
        }
    }
}
