/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface YProfileInfo {
        "apiKey": string;
        "channelDescription": string;
        "channelImage": string;
        "customDescription": boolean;
    }
    interface YSearch {
    }
    interface YVideoList {
        "apiKey": string;
        "channelId": string;
    }
}
declare global {
    interface HTMLYProfileInfoElement extends Components.YProfileInfo, HTMLStencilElement {
    }
    var HTMLYProfileInfoElement: {
        prototype: HTMLYProfileInfoElement;
        new (): HTMLYProfileInfoElement;
    };
    interface HTMLYSearchElement extends Components.YSearch, HTMLStencilElement {
    }
    var HTMLYSearchElement: {
        prototype: HTMLYSearchElement;
        new (): HTMLYSearchElement;
    };
    interface HTMLYVideoListElement extends Components.YVideoList, HTMLStencilElement {
    }
    var HTMLYVideoListElement: {
        prototype: HTMLYVideoListElement;
        new (): HTMLYVideoListElement;
    };
    interface HTMLElementTagNameMap {
        "y-profile-info": HTMLYProfileInfoElement;
        "y-search": HTMLYSearchElement;
        "y-video-list": HTMLYVideoListElement;
    }
}
declare namespace LocalJSX {
    interface YProfileInfo {
        "apiKey"?: string;
        "channelDescription"?: string;
        "channelImage"?: string;
        "customDescription"?: boolean;
    }
    interface YSearch {
    }
    interface YVideoList {
        "apiKey"?: string;
        "channelId"?: string;
    }
    interface IntrinsicElements {
        "y-profile-info": YProfileInfo;
        "y-search": YSearch;
        "y-video-list": YVideoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "y-profile-info": LocalJSX.YProfileInfo & JSXBase.HTMLAttributes<HTMLYProfileInfoElement>;
            "y-search": LocalJSX.YSearch & JSXBase.HTMLAttributes<HTMLYSearchElement>;
            "y-video-list": LocalJSX.YVideoList & JSXBase.HTMLAttributes<HTMLYVideoListElement>;
        }
    }
}
